name: phileo_downstream
channels:
  - nvidia
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python==3.9
  - numpy
  - pytorch==2.0.1
  - pytorch-cuda==11.7
  - pip:
    - buteo==0.9.22
    - colorama==0.4.6
    - llvmlite==0.40.1rc1
    - numba==0.57.0
    - psutil==5.9.5
    - torchvision==0.15.2
    - tqdm==4.65.0
    - ipykernel
    - torchmetrics
    - pandas

    